In this notebook i will practice data cleaning on a us job dataset from kaggle

**Simple Dashboard:** then i will answer 3–4 meaningful questions about the US job market using clean visuals.

**Q1. Which sectors are hiring most?**
Bar chart – top 10 sectors by listing count.

**Q2. What job types dominate?**
Pie or bar chart – Full Time vs Part Time vs Contract.

**Q3. Where are the jobs? (Top cities/states)**
Horizontal bar chart – top 15 locations by listing count.

**Q4. How did listings change over time?**
Line chart – listings per month. (Careful: this dataset only covers ~11 months.)

In [2]:
import pandas as pd
import numpy as np
import re
import plotly.express as px

In [3]:
import kagglehub
import os

path = kagglehub.dataset_download("PromptCloudHQ/us-jobs-on-monstercom")

files = os.listdir(path)
print(files)

df = pd.read_csv(os.path.join(path, files[0]))

df.head()

Warning: Looks like you're using an outdated `kagglehub` version (installed: 0.3.12), please consider upgrading to the latest version (1.0.0).
['monster_com-job_sample.csv']

,country,country_code,date_added,has_expired,job_board,job_description,job_title,job_type,location,organization,page_url,salary,sector,uniq_id
0,United States of America,US,NaN,No,jobs.monster.com,TeamSoft is seeing an IT Support Specialist to...,IT Support Technician Job in Madison,Full Time Employee,"Madison, WI 53702",NaN,http://jobview.monster.com/it-support-technici...,NaN,IT/Software Development,11d599f229a80023d2f40e7c52cd941e
1,United States of America,US,NaN,No,jobs.monster.com,The Wisconsin State Journal is seeking a flexi...,Business Reporter/Editor Job in Madison,Full Time,"Madison, WI 53708",Printing and Publishing,http://jobview.monster.com/business-reporter-e...,NaN,NaN,e4cbb126dabf22159aff90223243ff2a
2,United States of America,US,NaN,No,jobs.monster.com,Report this job About the Job DePuy Synthes Co...,Johnson & Johnson Family of Companies Job Appl...,"Full Time, Employee",DePuy Synthes Companies is a member of Johnson...,Personal and Household Services,http://jobview.monster.com/senior-training-lea...,NaN,NaN,839106b353877fa3d896ffb9c1fe01c0
3,United States of America,US,NaN,No,jobs.monster.com,Why Join Altec? If you’re considering a career...,Engineer - Quality Job in Dixon,Full Time,"Dixon, CA",Altec Industries,http://jobview.monster.com/engineer-quality-jo...,NaN,Experienced (Non-Manager),58435fcab804439efdcaa7ecca0fd783
4,United States of America,US,NaN,No,jobs.monster.com,Position ID# 76162 # Positions 1 State CT C...,Shift Supervisor - Part-Time Job in Camphill,Full Time Employee,"Camphill, PA",Retail,http://jobview.monster.com/shift-supervisor-pa...,NaN,Project/Program Management,64d0272dc8496abfd9523a8df63c184c

In [4]:
df

,country,country_code,date_added,has_expired,job_board,job_description,job_title,job_type,location,organization,page_url,salary,sector,uniq_id
0,United States of America,US,NaN,No,jobs.monster.com,TeamSoft is seeing an IT Support Specialist to...,IT Support Technician Job in Madison,Full Time Employee,"Madison, WI 53702",NaN,http://jobview.monster.com/it-support-technici...,NaN,IT/Software Development,11d599f229a80023d2f40e7c52cd941e
1,United States of America,US,NaN,No,jobs.monster.com,The Wisconsin State Journal is seeking a flexi...,Business Reporter/Editor Job in Madison,Full Time,"Madison, WI 53708",Printing and Publishing,http://jobview.monster.com/business-reporter-e...,NaN,NaN,e4cbb126dabf22159aff90223243ff2a
2,United States of America,US,NaN,No,jobs.monster.com,Report this job About the Job DePuy Synthes Co...,Johnson & Johnson Family of Companies Job Appl...,"Full Time, Employee",DePuy Synthes Companies is a member of Johnson...,Personal and Household Services,http://jobview.monster.com/senior-training-lea...,NaN,NaN,839106b353877fa3d896ffb9c1fe01c0
3,United States of America,US,NaN,No,jobs.monster.com,Why Join Altec? If you’re considering a career...,Engineer - Quality Job in Dixon,Full Time,"Dixon, CA",Altec Industries,http://jobview.monster.com/engineer-quality-jo...,NaN,Experienced (Non-Manager),58435fcab804439efdcaa7ecca0fd783
4,United States of America,US,NaN,No,jobs.monster.com,Position ID# 76162 # Positions 1 State CT C...,Shift Supervisor - Part-Time Job in Camphill,Full Time Employee,"Camphill, PA",Retail,http://jobview.monster.com/shift-supervisor-pa...,NaN,Project/Program Management,64d0272dc8496abfd9523a8df63c184c
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21995,United States of America,US,NaN,No,jobs.monster.com,This is a major premier Cincinnati based finan...,Assistant Vice President - Controller Job in C...,Full Time,"Cincinnati, OH",NaN,http://jobview.monster.com/Assistant-Vice-Pres...,"120,000.00 - 160,000.00 $ /yearbonus",NaN,a80bc8cc3a90c17eef418963803bc640
21996,United States of America,US,NaN,No,jobs.monster.com,Luxury homebuilder in Cincinnati seeking multi...,Accountant Job in Cincinnati,Full Time,"Cincinnati, OH 45236",Construction - Residential & Commercial/Office,http://jobview.monster.com/Accountant-Job-Cinc...,"45,000.00 - 60,000.00 $ /year",Manager (Manager/Supervisor of Staff),419a3714be2b30a10f628de207d041de
21997,United States of America,US,NaN,No,jobs.monster.com,RE: Adobe AEM- Client - Loca...,AEM/CQ developer Job in Chicago,Full Time,"Chicago, IL 60602",NaN,http://jobview.monster.com/AEM-CQ5-developer-J...,NaN,NaN,5a590350b73b2cec46b05750a208e345
21998,United States of America,US,NaN,No,jobs.monster.com,Jernberg Industries was established in 1937 an...,Electrician - Experienced Forging Electrician ...,Full Time Employee,"Chicago, IL 60609","Jernberg Industries, Inc.",http://jobview.monster.com/Electrician-Experie...,25.00 - 28.00 $ /hour,Installation/Maintenance/Repair,40161cf61c283af9dc2b0a62947a5f1b
21999,United States of America,US,NaN,No,jobs.monster.com,Contract AdministratorCan you be the point per...,Contract Administrator Job in Cincinnati,Full Time,"Cincinnati, OH",NaN,http://jobview.monster.com/Contract-Administra...,"40,000.00 - 46,000.00 $ /year+ annual bonus (u...",Experienced (Non-Manager),cb49f16ad72627b109e434e0cac97f7a

In [5]:
df.isnull().sum()

country                0
country_code           0
date_added         21878
has_expired            0
job_board              0
job_description        0
job_title              0
job_type            1628
location               0
organization        6867
page_url               0
salary             18554
sector              5194
uniq_id                0
dtype: int64

In [6]:
df.columns

Index(['country', 'country_code', 'date_added', 'has_expired', 'job_board',
       'job_description', 'job_title', 'job_type', 'location', 'organization',
       'page_url', 'salary', 'sector', 'uniq_id'],
      dtype='object')

**Q1. Which sectors are hiring most?**
Bar chart – top 10 sectors by listing count.

- for this we need the sector column and the count of the column

**Q2. What job types dominate?**
Pie or bar chart – Full Time vs Part Time vs Contract.

- for this we need the job_type and the count of the column

**Q3. Where are the jobs? (Top cities/states)**
geo map chart

- for this we need location and count

**Q4. How did listings change over time?**
Line chart – listings per month. (Careful: this dataset only covers ~11 months.)

- for this we need date_added, and sector but a lot of them are missing so im doubting if we can answer this question

lets remove unnececary columns

In [7]:
df.columns

Index(['country', 'country_code', 'date_added', 'has_expired', 'job_board',
       'job_description', 'job_title', 'job_type', 'location', 'organization',
       'page_url', 'salary', 'sector', 'uniq_id'],
      dtype='object')

In [8]:
df.head(3)

,country,country_code,date_added,has_expired,job_board,job_description,job_title,job_type,location,organization,page_url,salary,sector,uniq_id
0,United States of America,US,NaN,No,jobs.monster.com,TeamSoft is seeing an IT Support Specialist to...,IT Support Technician Job in Madison,Full Time Employee,"Madison, WI 53702",NaN,http://jobview.monster.com/it-support-technici...,NaN,IT/Software Development,11d599f229a80023d2f40e7c52cd941e
1,United States of America,US,NaN,No,jobs.monster.com,The Wisconsin State Journal is seeking a flexi...,Business Reporter/Editor Job in Madison,Full Time,"Madison, WI 53708",Printing and Publishing,http://jobview.monster.com/business-reporter-e...,NaN,NaN,e4cbb126dabf22159aff90223243ff2a
2,United States of America,US,NaN,No,jobs.monster.com,Report this job About the Job DePuy Synthes Co...,Johnson & Johnson Family of Companies Job Appl...,"Full Time, Employee",DePuy Synthes Companies is a member of Johnson...,Personal and Household Services,http://jobview.monster.com/senior-training-lea...,NaN,NaN,839106b353877fa3d896ffb9c1fe01c0

the unnececary collumns are: 'country', 'country_code', 'has_expired', 'job_board', 'organization', 'page_url', 'uniq_id', 'salary'

In [9]:
df = df.drop(columns=[
    'country',
    'country_code', 
    'has_expired', 
    'job_board', 
    'organization', 
    'page_url', 
    'uniq_id',
    'salary'
    ]
)

In [10]:
df.head(3)

,date_added,job_description,job_title,job_type,location,sector
0,NaN,TeamSoft is seeing an IT Support Specialist to...,IT Support Technician Job in Madison,Full Time Employee,"Madison, WI 53702",IT/Software Development
1,NaN,The Wisconsin State Journal is seeking a flexi...,Business Reporter/Editor Job in Madison,Full Time,"Madison, WI 53708",NaN
2,NaN,Report this job About the Job DePuy Synthes Co...,Johnson & Johnson Family of Companies Job Appl...,"Full Time, Employee",DePuy Synthes Companies is a member of Johnson...,NaN

now lets remove duplicates

In [11]:
dupe = df[df.duplicated()]
dupe

,date_added,job_description,job_title,job_type,location,sector
264,NaN,Join one of the fastest growing industries in ...,Student Truck Driver – Earn your CDL – Constru...,NaN,"Baker City, OR 97814",NaN
276,NaN,The Enrollment Agent I (EA I) supports Enrollm...,Enrollment Agent I* (-) Job in Denver,"Full Time, Employee","Denver, CO",Customer Support/Client Care
856,NaN,U.S. Security Care is seeking security officer...,Upscale Unarmed Security Officer Job in Newark,Part Time,"Newark, DE",Experienced (Non-Manager)
873,NaN,Security SpecialistMust have active Top Secret...,Security Specialist Job in Cincinnati,"Full Time , Temporary/Contract/Project","Cincinnati, OH 45215",Experienced (Non-Manager)
1035,NaN,Client Manager-Property & Casualty at Willis T...,Client Manager-Property & Casualty at Willis T...,Full Time,"Dallas, TX",Experienced (Non-Manager)
...,...,...,...,...,...,...
21942,NaN,Imagine Yourself in the Driver's Seat.Transpor...,Class A CDL Driver - TSC Job in Cincinnati,Full Time Employee,"Cincinnati, OH",Logistics/Transportation
21959,NaN,Senior Project Manager - Commercial Constructi...,Senior Project Manager - Commercial Constructi...,Full Time,"Cincinnati, OH 45206",Manager (Manager/Supervisor of Staff)
21963,NaN,Job Title:Consultant Security NetworkJob Descr...,Consultant Security Network Job in Cincinnati,Full Time Employee,Job Title:Consultant Security NetworkJob Descr...,IT/Software Development
21985,NaN,"We are a worldwide, leading manufacturer of ro...",General Manager of Sales & Marketing Job in Ci...,Full Time,"Cincinnati, OH","Executive (SVP, VP, Department Head, etc)"
21992,NaN,Sales Management TraineeLooking to use your sk...,Customer Service Professionals Consider a Care...,Full Time Employee,"Cincinnati, OH 45237",Field SalesGeneral/Other: Sales/Business Devel...

In [12]:
df = df.drop_duplicates()

lets clean while answering the questions so we dont do extra work

In [13]:
df.describe()

,date_added,job_description,job_title,job_type,location,sector
count,119,20817,20817,19297,20817,15895
unique,78,18744,18759,39,8423,163
top,3/21/2016,12N Horizontal Construction Engineers Job Desc...,Monster,Full Time,"Dallas, TX",Experienced (Non-Manager)
freq,4,104,300,6428,595,4299

lets drop date_added because its almost empty

In [14]:
df = df.drop('date_added', axis=1)

**Q1. Which sectors are hiring most?**
Bar chart – top 10 sectors by listing count.

- for this we need the sector column and the count of the column

In [15]:
counts = df['sector'].value_counts()
display(counts)

sector
Experienced (Non-Manager)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 4299
Medical/Health                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            1142
Entry Level                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               1142
Manager (Manager/Supervisor of Staff)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      874
IT/Software Development                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    839
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ...
Market ResearchGeneral/Other: Marketing/ProductProduct Management                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            1
Call CenterReservations/TicketingRetail Customer Service                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     1
Healthcare AidGeneral/Other: Medical/Health                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  1
Laboratory/PathologyNursingGeneral/Other: Medical/Health                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     1
Demonstrate the highest level of leadership and ethical standards, with a drive to uphold our “Culture of Can Do” Possess a passion for the beauty industry with the desire to constantly learn and then teach our store personnel and customers about our products Display strong organizational and planning skills with the ability to multi-task, problem-solve and act independently Self-starter with a drive to continuously learn and develop in career Must be 18 years of age or older Must have 3+ year(s) of retail sales/customer service experience Must have 1+ year(s) of managerial experience Licensed cosmetologist desirable but not required Work where we treat you and our customers as a priority-- Employee discount Free samples of many of our new products Opportunities to grow your career within the company On-going product knowledge programs and customer experience coaching Work in an  environment focused on and surrounded by beauty   Qualified applicants will receive consideration for employment without regard to their race, color, age, religion, nation origin, sex, sexual orientation, disability or other categories protected by law.   MONPOST         1
Name: count, Length: 163, dtype: int64

this is seriously dirty data, lets plot a bar chart to see whats happening

In [16]:
fig = px.bar(
    x=counts.index, 
    y=counts.values, 
    labels={'x': 'Category', 'y': 'Count'}
)

fig.show()

alot of columns are not standardized lets standerdize them

In [17]:
def normalize(val):
    if pd.isna(val): return np.nan
    val = val.lower()
    if "part" in val: return "part_time"
    if "full" in val: return "full_time"
    if "contract" in val or "temp" in val: return "contract"
    return "other"

df["job_type_clean"] = df["job_type"].apply(normalize)

In [18]:
df.job_type_clean.value_counts()

job_type_clean
full_time    18008
part_time      890
other          210
contract       189
Name: count, dtype: int64

In [19]:
df[df['job_type_clean'] == "other"].job_type.value_counts()

job_type
Employee              146
Per Diem, Employee     29
Per Diem               22
Per Diem Employee      11
Exempt                  1
Job Type Employee       1
Name: count, dtype: int64

lets do them same for sector, i am going to classify the sectors in these categories:

In [20]:
def classify_job(row):
    sector_val = str(row['sector']).lower() if pd.notna(row['sector']) else ''
    title_val = str(row['job_title']).lower() if pd.notna(row['job_title']) else ''
    desc_val = str(row['job_description']).lower()[:300] if pd.notna(row['job_description']) else ''
    
    # Combined text for sector inference (title most reliable, desc for backup)
    text = title_val + ' ' + desc_val

    seniority = np.nan
    if sector_val:
        if 'senior executive' in sector_val or 'president' in sector_val or 'cfo' in sector_val:
            seniority = 'Senior Executive'
        elif 'executive' in sector_val:
            seniority = 'Executive'
        elif 'manager' in sector_val:
            seniority = 'Manager'
        elif 'entry' in sector_val:
            seniority = 'Entry Level'
        elif 'experienced' in sector_val:
            seniority = 'Experienced (Non-Manager)'
        elif 'student' in sector_val:
            seniority = 'Student'
        elif 'intern' in sector_val:
            seniority = 'Intern'

    # SECTOR — try sector column first, fall back to title + description  #
    
    # If the sector value is a seniority label, skip it and go straight to text inference
    is_seniority_label = seniority is not np.nan
    
    sector = np.nan

    # --- Pass 1: from sector column (skip if it's a seniority label) ---
    if sector_val and not is_seniority_label:
        if any(x in sector_val for x in [
            'it/', 'software', 'hardware', 'network', 'database', 'developer',
            'systems admin', 'tech support', 'information tech', 'computer',
            'cyber', 'devops', 'cloud', 'qa/', 'quality assurance', 'telecom'
        ]):
            sector = 'IT & Software'

        elif any(x in sector_val for x in [
            'engineer', 'civil', 'structural', 'mechanical', 'electrical',
            'chemical', 'aerospace', 'industrial', 'packaging', 'petroleum'
        ]):
            sector = 'Engineering'

        elif any(x in sector_val for x in [
            'medical', 'health', 'nurs', 'pharma', 'lab/', 'laboratory',
            'dental', 'physician', 'therapy', 'therapist', 'clinical',
            'biotech', 'social work', 'mental health', 'optom', 'veterin',
            'radiol', 'pathol', 'surgeon', 'surgery'
        ]):
            sector = 'Healthcare'

        elif any(x in sector_val for x in [
            'sales', 'marketing', 'business dev', 'advertising',
            'public relations', 'brand', 'market research', 'e-commerce'
        ]):
            sector = 'Sales & Marketing'

        elif any(x in sector_val for x in [
            'financ', 'bank', 'insurance', 'invest', 'audit', 'tax',
            'payroll', 'actuar', 'mortgage', 'credit', 'wealth',
            'budget', 'controller', 'treasury', 'accountant', 'accounting'
        ]):
            sector = 'Finance & Accounting'

        elif any(x in sector_val for x in [
            'construct', 'maintenance', 'repair', 'install', 'electrician',
            'plumb', 'hvac', 'carpenter', 'weld', 'facilities', 'foreman'
        ]):
            sector = 'Construction & Trades'

        elif any(x in sector_val for x in [
            'logistic', 'transport', 'driver', 'warehouse', 'supply chain',
            'shipping', 'freight', 'delivery', 'fleet', 'aviation',
            'dispatch', 'procurement', 'purchasing'
        ]):
            sector = 'Logistics & Transport'

        elif any(x in sector_val for x in [
            'customer support', 'customer service', 'client care',
            'call center', 'reservations', 'help desk'
        ]):
            sector = 'Customer Service'

        elif any(x in sector_val for x in [
            'retail', 'food service', 'hospitality', 'restaurant',
            'hotel', 'travel', 'tourism', 'culinary', 'catering'
        ]):
            sector = 'Retail & Hospitality'

        elif any(x in sector_val for x in [
            'educat', 'teach', 'tutor', 'academic', 'curriculum',
            'school', 'university', 'faculty'
        ]):
            sector = 'Education'

        elif any(x in sector_val for x in [
            'human resource', ' hr/', 'recruiting', 'talent acqui',
            'admin', 'clerical', 'receptionist', 'office manage',
            'executive assist', 'data entry', 'secretar'
        ]):
            sector = 'Admin & HR'

        elif any(x in sector_val for x in [
            'legal', 'attorney', 'paralegal', 'compliance',
            'litigation', 'regulatory'
        ]):
            sector = 'Legal & Compliance'

        elif any(x in sector_val for x in [
            'project/program', 'program manag', 'project manag',
            'business/strategic', 'strategy', 'operations manag',
            'business analyst', 'scrum', 'agile'
        ]):
            sector = 'Project & Strategy'

        elif any(x in sector_val for x in [
            'design', 'creative', 'art direct', 'graphic', 'media',
            'journalism', 'writing', 'editor', 'content', 'publishing',
            'photography', 'broadcast'
        ]):
            sector = 'Creative & Media'

        elif any(x in sector_val for x in [
            'non-profit', 'nonprofit', 'government', 'military',
            'public sector', 'community'
        ]):
            sector = 'Non-profit & Government'

        elif any(x in sector_val for x in [
            'manufacturing', 'assembl', 'production',
            'quality control', 'lean', 'six sigma'
        ]):
            sector = 'Manufacturing'

        elif any(x in sector_val for x in [
            'security', 'protective', 'guard', 'surveillance'
        ]):
            sector = 'Security & Protective'

    #infer from job_title + job_description if still unknown
    if pd.isna(sector):
        if any(x in text for x in [
            'software', 'developer', 'devops', 'cloud', 'it support',
            'network admin', 'database', 'cybersecurity', 'systems admin',
            'data scientist', 'machine learning', 'backend', 'frontend',
            'full stack', 'helpdesk', 'web developer', 'matlab',
            'java ', 'python', '.net', 'sap', 'salesforce', 'erp'
        ]):
            sector = 'IT & Software'

        elif any(x in text for x in [
            'mechanical engineer', 'electrical engineer', 'civil engineer',
            'chemical engineer', 'aerospace engineer', 'structural engineer',
            'process engineer', 'quality engineer', 'packaging engineer',
            'environmental engineer', 'petroleum engineer'
        ]):
            sector = 'Engineering'

        elif any(x in text for x in [
            'nurse', 'physician', 'doctor', 'medical', 'clinical', 'dental',
            'pharmacy', 'therapist', 'healthcare', 'health care', 'surgeon',
            'caregiver', 'home health', 'patient', 'hospital', 'icu',
            'emt', 'paramedic', 'radiolog', 'patholog'
        ]):
            sector = 'Healthcare'

        elif any(x in text for x in [
            'accountant', 'accounting', 'financial analyst', 'finance manager',
            'auditor', 'tax ', 'payroll', 'bookkeeper', 'controller',
            'investment', 'mortgage', 'actuary', 'underwriter', 'credit analyst'
        ]):
            sector = 'Finance & Accounting'

        elif any(x in text for x in [
            'sales rep', 'sales manager', 'account executive', 'territory sales',
            'marketing manager', 'digital marketing', 'brand manager', 'seo',
            'social media', 'business development', 'sales support'
        ]):
            sector = 'Sales & Marketing'

        elif any(x in text for x in [
            'construction', 'electrician', 'plumber', 'hvac', 'carpenter',
            'welder', 'foreman', 'maintenance tech', 'facilities manager',
            'roofer', 'pipefitter', 'millwright', 'handyman'
        ]):
            sector = 'Construction & Trades'

        elif any(x in text for x in [
            'truck driver', 'cdl', 'warehouse', 'logistics', 'supply chain',
            'shipping', 'freight', 'dispatcher', 'forklift', 'delivery driver',
            'mailroom', 'procurement', 'purchasing', 'distribution'
        ]):
            sector = 'Logistics & Transport'

        elif any(x in text for x in [
            'customer service', 'customer support', 'call center',
            'client services', 'customer care', 'service rep'
        ]):
            sector = 'Customer Service'

        elif any(x in text for x in [
            'restaurant', 'chef', 'cook', 'bartender', 'server', 'hotel',
            'hospitality', 'food service', 'barista', 'cashier', 'retail',
            'store manager', 'shift supervisor'
        ]):
            sector = 'Retail & Hospitality'

        elif any(x in text for x in [
            'teacher', 'instructor', 'professor', 'tutor', 'educator',
            'curriculum', 'preschool', 'kindergarten', 'e-learning', 'faculty'
        ]):
            sector = 'Education'

        elif any(x in text for x in [
            'human resources', 'recruiter', 'talent acquisition',
            'office manager', 'administrative assistant', 'receptionist',
            'data entry', 'executive assistant', 'office admin'
        ]):
            sector = 'Admin & HR'

        elif any(x in text for x in [
            'attorney', 'lawyer', 'paralegal', 'legal', 'compliance officer',
            'contract admin', 'litigation', 'counsel'
        ]):
            sector = 'Legal & Compliance'

        elif any(x in text for x in [
            'project manager', 'program manager', 'scrum master', 'agile',
            'business analyst', 'product manager', 'product owner', 'pmo'
        ]):
            sector = 'Project & Strategy'

        elif any(x in text for x in [
            'graphic designer', 'ux designer', 'ui designer', 'copywriter',
            'journalist', 'content writer', 'art director', 'photographer',
            'videographer', 'animator', 'creative director'
        ]):
            sector = 'Creative & Media'

        elif any(x in text for x in [
            'security officer', 'security guard', 'loss prevention',
            'surveillance', 'law enforcement', 'investigator'
        ]):
            sector = 'Security & Protective'

        elif any(x in text for x in [
            'assembler', 'assembly line', 'machine operator', 'quality control',
            'lean manufacturing', 'six sigma', 'plant manager', 'production line'
        ]):
            sector = 'Manufacturing'

    return pd.Series({
        'sector_clean': sector,
        'seniority': seniority
    })


# Apply — axis=1 passes the full row
df[['sector_clean', 'seniority']] = df.apply(classify_job, axis=1)

print(df['sector_clean'].value_counts())
print(f"\nSector nulls remaining: {df['sector_clean'].isna().sum()}")
print(f"Seniority nulls:        {df['seniority'].isna().sum()}")

sector_clean
Healthcare                 2958
IT & Software              2657
Construction & Trades      1657
Sales & Marketing          1489
Retail & Hospitality       1336
Project & Strategy         1280
Finance & Accounting       1259
Logistics & Transport       879
Admin & HR                  798
Manufacturing               686
Legal & Compliance          665
Customer Service            664
Engineering                 360
Security & Protective       359
Education                   183
Creative & Media             58
Non-profit & Government       2
Name: count, dtype: int64

Sector nulls remaining: 3527
Seniority nulls:        14333

In [21]:
counts = df.sector_clean.value_counts()

fig = px.bar(
    x=counts.index,
    y=counts.values,
    labels={"x": "Sector", "y": "Count"},
    title="Sector counts"
)

fig.show()

In [22]:
df['sector_clean'].value_counts()

sector_clean
Healthcare                 2958
IT & Software              2657
Construction & Trades      1657
Sales & Marketing          1489
Retail & Hospitality       1336
Project & Strategy         1280
Finance & Accounting       1259
Logistics & Transport       879
Admin & HR                  798
Manufacturing               686
Legal & Compliance          665
Customer Service            664
Engineering                 360
Security & Protective       359
Education                   183
Creative & Media             58
Non-profit & Government       2
Name: count, dtype: int64

In [23]:
df.seniority.value_counts()

seniority
Manager             5182
Entry Level         1147
Student               87
Executive             62
Senior Executive       6
Name: count, dtype: int64

In [24]:
df['sector_clean'].isna().sum()

np.int64(3527)

In [25]:
df['seniority'].isna().sum()

np.int64(14333)

In [26]:
df[df['sector_clean'] == 'Other']['sector'].value_counts().head(20)

Series([], Name: count, dtype: int64)

lets parse the location column

In [27]:
def parse_location(val):
    if pd.isna(val): 
        return np.nan, np.nan
    # Remove ZIP codes
    val = re.sub(r'\s+\d{5}(-\d{4})?$', '', val.strip())
    parts = val.split(',')
    if len(parts) == 2:
        return parts[0].strip(), parts[1].strip()
    return val.strip(), np.nan

df[['city', 'state']] = pd.DataFrame(
    df['location'].apply(parse_location).tolist(),
    index=df.index
)

# Verify
print(df[['location', 'city', 'state']].head(10))
print(f"State nulls: {df['state'].isna().sum()}")

                                            location  \
0                                  Madison, WI 53702
1                                  Madison, WI 53708
2  DePuy Synthes Companies is a member of Johnson...
3                                          Dixon, CA
4                                       Camphill, PA
5                                Charlottesville, VA
6                            Contact name Tony Zerio
7                                   Austin, TX 73301
8                                   Austin, TX 78746
9                                   Chesterfield, MO

                                                city state
0                                            Madison    WI
1                                            Madison    WI
2  DePuy Synthes Companies is a member of Johnson...   NaN
3                                              Dixon    CA
4                                           Camphill    PA
5                                    Charlottesville    VA
6                            Contact name Tony Zerio   NaN
7                                             Austin    TX
8                                             Austin    TX
9                                       Chesterfield    MO
State nulls: 3012

In [36]:
df

,job_description,job_title,job_type,location,sector,job_type_clean,sector_clean,seniority,city,state
0,TeamSoft is seeing an IT Support Specialist to...,IT Support Technician Job in Madison,Full Time Employee,"Madison, WI 53702",IT/Software Development,full_time,IT & Software,NaN,Madison,WI
1,The Wisconsin State Journal is seeking a flexi...,Business Reporter/Editor Job in Madison,Full Time,"Madison, WI 53708",NaN,full_time,Creative & Media,NaN,Madison,WI
2,Report this job About the Job DePuy Synthes Co...,Johnson & Johnson Family of Companies Job Appl...,"Full Time, Employee",DePuy Synthes Companies is a member of Johnson...,NaN,full_time,NaN,NaN,DePuy Synthes Companies is a member of Johnson...,NaN
3,Why Join Altec? If you’re considering a career...,Engineer - Quality Job in Dixon,Full Time,"Dixon, CA",Experienced (Non-Manager),full_time,NaN,Manager,Dixon,CA
4,Position ID# 76162 # Positions 1 State CT C...,Shift Supervisor - Part-Time Job in Camphill,Full Time Employee,"Camphill, PA",Project/Program Management,full_time,Project & Strategy,NaN,Camphill,PA
...,...,...,...,...,...,...,...,...,...,...
21995,This is a major premier Cincinnati based finan...,Assistant Vice President - Controller Job in C...,Full Time,"Cincinnati, OH",NaN,full_time,Finance & Accounting,NaN,Cincinnati,OH
21996,Luxury homebuilder in Cincinnati seeking multi...,Accountant Job in Cincinnati,Full Time,"Cincinnati, OH 45236",Manager (Manager/Supervisor of Staff),full_time,Finance & Accounting,Manager,Cincinnati,OH
21997,RE: Adobe AEM- Client - Loca...,AEM/CQ developer Job in Chicago,Full Time,"Chicago, IL 60602",NaN,full_time,IT & Software,NaN,Chicago,IL
21998,Jernberg Industries was established in 1937 an...,Electrician - Experienced Forging Electrician ...,Full Time Employee,"Chicago, IL 60609",Installation/Maintenance/Repair,full_time,Construction & Trades,NaN,Chicago,IL
21999,Contract AdministratorCan you be the point per...,Contract Administrator Job in Cincinnati,Full Time,"Cincinnati, OH",Experienced (Non-Manager),full_time,Legal & Compliance,Manager,Cincinnati,OH